var myChart3=echarts.init(document.getElementById('sunburst_00'));
    var data=[
        {
        name:'雄鹿',
        children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:25.7',value:80},
                {name:'失误:14.08',value:80},
                {name:'抢断:8.19',value:80},
                {name:'盖帽:4.56',value:80},
                {name:'犯规:17.10',value:80},
                {name:'得分:119.6',value:100}
                ]
            },
    ]
    },
        {
        name:'篮网',
        children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:26.7',value:80},
                {name:'失误:13.85',value:80},
                {name:'抢断:6.82',value:80},
                {name:'盖帽:5.18',value:80},
                {name:'犯规:19.08',value:80},
                {name:'得分:118.6',value:100}
                ]
            },
    ]
    },
        {
    name:'爵士',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:23.7',value:80},
                {name:'失误:14.08',value:80},
                {name:'抢断:6.50',value:80},
                {name:'盖帽:5.38',value:80},
                {name:'犯规:18.88',value:80},
                {name:'得分:116.5',value:100}
                ]
            },
    ]
    },
        {
    name:'掘金',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:27.2',value:80},
                {name:'失误:13.58',value:80},
                {name:'抢断:8.02',value:80},
                {name:'盖帽:4.55',value:80},
                {name:'犯规:18.83',value:80},
                {name:'得分:115.5',value:100}
                ]
            },
    ]
    },
    {
    name:'鹈鹕',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:26.1',value:80},
                {name:'失误:14.52',value:80},
                {name:'抢断:7.28',value:80},
                {name:'盖帽:4.30',value:80},
                {name:'犯规:17.93',value:80},
                {name:'得分:115.0',value:100}
                ]
            },
    ]
    },
    {
    name:'快船',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:24.5',value:80},
                {name:'失误:12.98',value:80},
                {name:'抢断:7.08',value:80},
                {name:'盖帽:4.16',value:80},
                {name:'犯规:19.53',value:80},
                {name:'得分:114.9',value:100}
                ]
            },
    ]
    },
    {
    name:'国王',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:25.5',value:80},
                {name:'失误:13.20',value:80},
                {name:'抢断:7.17',value:80},
                {name:'盖帽:4.85',value:80},
                {name:'犯规:19.63',value:80},
                {name:'得分:114.6',value:100}
                ]
            },
    ]
    },
    {
    name:'奇才',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:25.0',value:80},
                {name:'失误:14.95',value:80},
                {name:'抢断:7.29',value:80},
                {name:'盖帽:3.85',value:80},
                {name:'犯规:21.71',value:80},
                {name:'得分:114.4',value:100}
                ]
            },
    ]
    },
    {
    name:'开拓者',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:20.7',value:80},
                {name:'失误:11.34',value:80},
                {name:'抢断:7.02',value:80},
                {name:'盖帽:5.08',value:80},
                {name:'犯规:19.08',value:80},
                {name:'得分:114.4',value:100}
                ]
            },
    ]
    },
    {
    name:'太阳',
    children:[
            {name:'汇总',value:500,
                children:[
                {name:'助攻:27.1',value:80},
                {name:'失误:13.00',value:80},
                {name:'抢断:7.20',value:80},
                {name:'盖帽:4.19',value:80},
                {name:'犯规:19.36',value:80},
                {name:'得分:114.2',value:100}
                ]
            },
    ]
    },
        ]
    option={
        series:{
            type:'sunburst',
            data:data,
            radius:[0,'90%'],
            sort:null,
            emphasis:{
                focus:'ancestor'
            },
            label:{
                rotate:'radial'
            }
        }
    };
    myChart3.setOption(option);